/**
 * 时间管理系统-swagger接口测试工具
 * SpringBoot3 集成 Swagger3接口文档
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swagger);
  }
}(this, function(expect, Swagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Swagger.InsightsControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InsightsControllerApi', function() {
    describe('getPList', function() {
      it('should call getPList successfully', function(done) {
        //uncomment below and update the code to test getPList
        //instance.getPList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTagList', function() {
      it('should call getTagList successfully', function(done) {
        //uncomment below and update the code to test getTagList
        //instance.getTagList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTaskCompletion', function() {
      it('should call getTaskCompletion successfully', function(done) {
        //uncomment below and update the code to test getTaskCompletion
        //instance.getTaskCompletion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTaskDistribution', function() {
      it('should call getTaskDistribution successfully', function(done) {
        //uncomment below and update the code to test getTaskDistribution
        //instance.getTaskDistribution(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTaskTimeSpent', function() {
      it('should call getTaskTimeSpent successfully', function(done) {
        //uncomment below and update the code to test getTaskTimeSpent
        //instance.getTaskTimeSpent(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTaskTrend', function() {
      it('should call getTaskTrend successfully', function(done) {
        //uncomment below and update the code to test getTaskTrend
        //instance.getTaskTrend(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
