/**
 * 时间管理系统-swagger接口测试工具
 * SpringBoot3 集成 Swagger3接口文档
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Todos model module.
 * @module model/Todos
 * @version v1
 */
class Todos {
    /**
     * Constructs a new <code>Todos</code>.
     * @alias module:model/Todos
     */
    constructor() { 
        
        Todos.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Todos</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Todos} obj Optional instance to populate.
     * @return {module:model/Todos} The populated <code>Todos</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Todos();

            if (data.hasOwnProperty('todoId')) {
                obj['todoId'] = ApiClient.convertToType(data['todoId'], 'Number');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('createTime')) {
                obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Number');
            }
            if (data.hasOwnProperty('done')) {
                obj['done'] = ApiClient.convertToType(data['done'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Todos</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Todos</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }

        return true;
    }


}



/**
 * @member {Number} todoId
 */
Todos.prototype['todoId'] = undefined;

/**
 * @member {Number} userId
 */
Todos.prototype['userId'] = undefined;

/**
 * @member {String} text
 */
Todos.prototype['text'] = undefined;

/**
 * @member {Number} createTime
 */
Todos.prototype['createTime'] = undefined;

/**
 * @member {Boolean} done
 */
Todos.prototype['done'] = undefined;






export default Todos;

